services:
  goCV:
    image: kjarosh/latex:2025.1-small
    container_name: goCV
    working_dir: /out
    volumes:
      - ./out:/out
      - ./cv-gen:/goCV
      - ./content.yaml:/content.yaml
    command: > 
      sh -c "tlmgr update --self --all &&
             tlmgr install latexmk &&
             /goCV /content.yaml"
