services:
  goCV:
    image: kjarosh/latex:2025.1-small
    container_name: goCV
    working_dir: /output
    volumes:
      - ./output:/output
      - ./goCV:/goCV
      - ./content.yaml:/content.yaml
    command: > 
      sh -c "tlmgr update --self --all &&
             tlmgr install latexmk &&
             /goCV --output ./ /content.yaml"
