name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: Build binary
        run: go build -o main ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-binary
          path: main
